"""Local defaults. Terraform replaces this module inside the Lambda@Edge zip."""

CONFIG_BUCKET = ""
CONFIG_KEY = "redirects.conf"
CONFIG_REGION = "us-east-1"
CONFIG_CHECK_INTERVAL_SECONDS = 30
FALLBACK_BEHAVIOR = "not_found"
FALLBACK_STATUS_CODE = 404
FALLBACK_BODY = "No redirect rule matched this request."
REDIRECT_CACHE_SECONDS = 300
TRUSTED_EDGE_HEADER_NAME = "x-redirect-edge-token"
TRUSTED_EDGE_HEADER_VALUE = ""
ALLOWED_REDIRECT_HOSTS = ""
REQUIRE_HTTPS_REDIRECT_TARGETS = True
MAX_REDIRECT_CONFIG_BYTES = 262144
ENABLE_DIAGNOSTIC_HEADERS = False
